name: Publish Docker image and Create Branch with Commit Hash
on:
 push:
   branches: ['main']

jobs:

 push_to_registry:
   name: Push Docker image to Docker Hub
   runs-on: ubuntu-latest
   
   steps:
   - name: Check out the repo
     uses: actions/checkout@v3
     
   - name: Log in to Docker Hub
     uses: docker/login-action@v2
     with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       
   - name: Extract metadata for Docker
     id: meta
     uses: docker/metadata-action@v4
     with:
       images: krisneonploy/dockerbuild
       
   - name: Build and push Docker image
     uses: docker/build-push-action@v4
     with:
       context: .
       push: true
       tags: ${{ steps.meta.outputs.tags }}
       labels: ${{ steps.meta.outputs.labels }}
       
   - name: Create New Branch with Commit Hash
     env:
       GH_PAT: ${{ secrets.GH_PAT }}
     run: |
       git config user.name github-actions
       git config user.email github-actions@github.com
       COMMIT_HASH=$(git rev-parse --short HEAD)
       NEW_BRANCH_NAME="log-$COMMIT_HASH"
       git checkout -b $NEW_BRANCH_NAME
       git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git $NEW_BRANCH_NAME
