name: commitlog

on:
  schedule:
    - cron: '*/15 * * * *' # รันทุก 15 นาที

jobs:

  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Run Super-Linter
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
     
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
     
    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
     
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
       
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: krisneonploy/schedule 
       
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
       
    - name: Create New Branch with Commit Hash
      if: always() # สร้าง branch ทุกครั้งที่ workflow รัน
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name dornrock123
        git config user.email krisd3214@gmail.com
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        NEW_BRANCH_NAME="log-$(echo "$COMMIT_MESSAGE" | tr '[:upper:]' '[:lower:]' | tr '[:space:]' '-' | tr '[:punct:]' '-')"
        git checkout -b $NEW_BRANCH_NAME
        git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git $NEW_BRANCH_NAME
